kind: pipeline
name: default

steps:

  - name: prepare
    image: node
    commands:
    - cd frontend
    - npm install
    - npm test
    - npm run build

  - name: test
    image: drailing/go_packr_zip
    environment:
      GO111MODULE: on
    commands:
    - make test 
    
  - name: build
    image: drailing/go_packr_zip
    environment:
      GO111MODULE: on
    commands:
      - make build-all
      - make zip-all
    when:
      branch: master

  - name: dockerize
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: drailing/1chatroom
      build_args: 
        - CHATROOM_BIN_ARG=${DRONE_REPO_NAME}-${DRONE_TAG=master}-alpine
      tags:
        - '${DRONE_TAG=latest}'
    when:
      branch: master

  - name: github_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: 
        - release/*
    when:
      event: tag