kind: pipeline
name: default

steps:

  - name: prepare
    image: node
    commands:
    - cd frontend
    - cd npm install

  - name: test
    image: drailing/go_packr_zip
    environment:
      GO111MODULE: on
    commands:
    - make test 
    
  - name: build
    image: drailing/go_packr_zip
    environment:
      GO111MODULE: on
    commands:
      - make build-all
      - make zip-all

  - name: dockerize
    image: plugins/docker
    environment:
      CHATROOM_BIN: ${DRONE_REPO_NAME}-${DRONE_TAG}-alpine
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: drailing/1chatroom
      auto_tag: true

  - name: github_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: 
        - release/*
    when:
      event: tag